Postgres docker
morijyobi-2021-itadv3/JobReportManagement pull request #11
Opened 2021-11-25 03:38 UTC by hikaru0112

## 解決する
#10 

## やったこと
- ローカル上でpostgresを使用できるようにしました

2021-11-29 02:19 UTC, suzuryo-morijyobi requested changes

2021-11-29 02:19 UTC, suzuryo-morijyobi commented on docker-compose.yml
> +        ipv4_address: 172.30.0.2
固定IPじゃなくて、dns的にホスト名で実装できると素敵

2021-11-29 02:19 UTC, suzuryo-morijyobi commented on app.py
>      app.run(debug=True)
行末には、必ず改行を入れる癖を付けるとよい

2021-11-29 02:19 UTC, suzuryo-morijyobi commented on model/db.py
> +        user = 'admin',
環境変数で指定する

2021-12-01 02:42 UTC, hikaru0112 commented
## 解決する
#10 

コードレビューで指摘された箇所を修正しました。

2021-12-02 02:22 UTC, hikaru0112 commented on docker-compose.yml
> +        ipv4_address: 172.30.0.2
ホスト名で接続するように変更しました

2021-12-02 02:22 UTC, hikaru0112 commented on docker-compose.yml
> +        ipv4_address: 172.30.0.2
該当箇所を改行しました

2021-12-02 02:30 UTC, suzuryo-morijyobi requested changes

2021-12-02 02:30 UTC, suzuryo-morijyobi commented on .gitignore
> +dockerfile
`#other` 部分に追加した ignore の意図が不明です

2021-12-02 02:30 UTC, suzuryo-morijyobi commented on app.py
> +
この空行は何？

2021-12-02 02:30 UTC, suzuryo-morijyobi commented on docker-compose.yml
> +      - PSQL_DB_DOCKER_PORT=$PSQL_DB_DOCKER_PORT
この環境変数は、どのようにして設定しますか？

2021-12-02 02:30 UTC, suzuryo-morijyobi commented on docker-compose.yml
> +    hostname: 'db'
service が db になってるけど、 改めて hostname: 'db' を指定する必要があるの？

2021-12-02 02:30 UTC, suzuryo-morijyobi commented on docker-compose.yml
> +    restart: always
`restart: always` を付けてる理由は何ですか？

2021-12-02 02:30 UTC, suzuryo-morijyobi commented on docker-compose.yml
> +  adminer:
adminer コンテナは今回のissueの要件には入っていないです

2021-12-02 02:30 UTC, suzuryo-morijyobi commented on docker-compose.yml
> +      - '5433:5432'
左辺が5433で、右辺が5432で、数字の1つ違うポートを指定している理由は何ですか？

2021-12-02 03:41 UTC, hikaru0112 commented on docker-compose.yml
> +      - '5433:5432'
ローカルPCでのDBアクセスの際にローカルPCに存在しているDBのポートとコンテナのPostgresのポートが重複してしまい、どちらかのDアクセスできなくなってしまうためにポートフォワーディングを使用しました。

2021-12-02 04:28 UTC, suzuryo-morijyobi commented on docker-compose.yml
> +      - '5433:5432'
そもそも、dbコンテナの5432ポートを、ホスト側に出す必要があるかどうか？

2021-12-06 03:30 UTC, hikaru0112 commented on docker-compose.yml
> +      - '5433:5432'
ホスト側で操作できればデバックも楽ですし、
一番の大きな理由では自分の環境（ホスト側）では5432ポートを使用しているため、衝突を回避するために変更しました。

2021-12-08 02:49 UTC, suzuryo-morijyobi commented on docker-compose.yml
> +      - '5433:5432'
windows側から直接dbコンテナにpsqlで接続しないならば、ホスト側にdbコンテナのポートを開く必要はないです。

- dbコンテナのbashからpsqlを実行する
- 初期化やseedsに必要なsqlは `docker-entrypoint-initdb.d` フォルダを利用する

ことで、windows側からdbコンテナにpsql接続する必要がなくなると思います

2021-12-09 02:39 UTC, suzuryo-morijyobi commented on docker-compose.yml
> +      - '5433:5432'
JetBrains の PyCharm や DataGrip などの開発環境を利用して、ツールから直接5432を使いたい場合は、開いておきましょう。

2021-12-09 02:51 UTC, hikaru0112 commented
# やったこと
* dockerignoreファイルの追加
* データベース名指定

2021-12-09 02:56 UTC, hikaru0112 commented on docker-compose.yml
> +      - '5433:5432'
プロジェクトの方針で、開発環境でのデバッグなどがしやすいという観点から、ポートは結局開き、ポート番号は`5432`を使用することになりました。

2021-12-09 03:12 UTC, hikaru0112 commented on docker-compose.yml
> +  adminer:
コンテナのデバックの際に使用したまま削除するのを忘れていました。
削除しました。

2021-12-09 03:14 UTC, hikaru0112 commented on docker-compose.yml
> +    restart: always
特に理由はなかったです。
削除しました。

2021-12-09 03:15 UTC, hikaru0112 commented on docker-compose.yml
> +    hostname: 'db'
コンテナ名がホスト名になるのが知らなく、いちいち指定しないといけないと思っていました。
必要なかったので削除しました。

2021-12-09 03:16 UTC, hikaru0112 commented on docker-compose.yml
> +      - PSQL_DB_DOCKER_PORT=$PSQL_DB_DOCKER_PORT
.envファイルを使用して設定するようにしました。

2021-12-09 03:17 UTC, hikaru0112 commented on .gitignore
> +dockerfile
誤って追加したままでした。
削除しました。

2021-12-09 03:18 UTC, hikaru0112 commented on app.py
> +
誤って空行を追加していました。
削除しました。

2021-12-13 02:28 UTC, merged