開発環境のDocker化とPostgresの設定
morijyobi-2021-itadv3/JobReportManagement pull request #14
Opened 2021-12-02 03:21 UTC by tora87

## 関連
close #10 について

## 実装内容
- 現在の開発環境をDockerコンテナ化
- PostgreSQLのデータベースコンテナの作成
- flaskでデータベースから値を取得

2021-12-06 02:43 UTC, suzuryo-morijyobi requested changes

2021-12-06 02:43 UTC, suzuryo-morijyobi commented on docker-compose.yml
> +    image: postgres:13.5
`postgres:13` じゃなくて `postgres:13.5` にしたのは、どんな理由ですか？

2021-12-06 02:43 UTC, suzuryo-morijyobi commented on docker-compose.yml
> +    environment:
環境変数は、 .env ファイルを使った方がよいと思います

2021-12-06 02:43 UTC, suzuryo-morijyobi commented on model/db.py
> +        host = 'db',
pythonの中も、ハードコードせずに、環境変数から指定の値を読み込むようにしましょう

2021-12-06 02:47 UTC, tora87 commented on docker-compose.yml
> +    image: postgres:13.5
Heroku内のPostgresのバージョンに合わせました。

2021-12-06 02:59 UTC, suzuryo-morijyobi commented on docker-compose.yml
> +    image: postgres:13.5
了解です！

2021-12-08 02:51 UTC, suzuryo-morijyobi commented on docker-compose.yml
> +      - "5433:5432"
ホスト側にdbコンテナのpostを開いてるのは、何か理由がありますか？

2021-12-09 02:39 UTC, tora87 commented
Dockerについて3人とも同じタスクで進め、プルリクエストを作っていましたがマージするのは代表者一人のプルリクエストだけで良いので、このプルリクエストを閉じます。

2021-12-09 02:39 UTC, closed without merging