開発環境をDockerで動作するようにした
morijyobi-2021-itadv3/JobReportManagement pull request #15
Opened 2021-12-06 02:42 UTC by kentamjb

#10 
開発用のコンテナと、postgresのコンテナを作成した
- [x] 開発環境のdocker化
- [x] postgresのdocker化
- [x] dbから取得したデータをhtmlで表示

2021-12-06 02:54 UTC, suzuryo-morijyobi requested changes

2021-12-06 02:54 UTC, suzuryo-morijyobi commented on docker-compose.yml
> +    environment:
環境変数は、直書きせずに、.env ファイル等を通じてコンテナに渡すようにしましょう

2021-12-06 02:54 UTC, suzuryo-morijyobi commented on model/db.py
> +        host = 'db',
DBへの接続情報は、環境変数を通じて取得しましょう

2021-12-09 02:39 UTC, kentamjb commented
代表して光さんのプルリクエストを採用するので、私のプルリクエストは閉じます

2021-12-09 02:39 UTC, closed without merging