CSVユーザ追加機能の実装
morijyobi-2021-itadv3/JobReportManagement pull request #22
Opened 2021-12-26 10:44 UTC by tora87

# CSVユーザー追加機能の実装
#20 について

### 主な作業内容
- 大まかな画面のレイアウトと装飾
- CSVテンプレートのとダウンロード機能簿ｎ作成
- プレビュー＆バリデーションチェック機能の作成
- メール送信機能の作成
- ユーザー追加機能の作成
- 学生追加機能の作成

2021-12-30 15:55 UTC, youhei-takahashi requested changes
ざっと見て気になったところにコメントを入れています。
ご確認ください。

全体的に異常系の処理が甘いように感じました。
DBを引いて0件だった時や `null` や `None` , `空白` などの正常ではないデータが入ってきた時の処理を検討しましょう。

2021-12-30 15:55 UTC, youhei-takahashi commented on static/js/add_user.js
> +      }
下記のようにcsvの最後の行に改行が入るとデータが1件分多く計算されて、`ユーザを追加する`ボタンが活性化されません。
![image](https://user-images.githubusercontent.com/50701460/147765269-d3a5050b-37a4-417a-84d5-f168b66cd13f.png)

![image](https://user-images.githubusercontent.com/50701460/147765218-d8c85530-9086-4ff9-bfa7-8a637f5b30a9.png)

2021-12-30 15:55 UTC, youhei-takahashi commented on model/users.py
> +  sql = 'INSERT INTO users (mail, password, salt, name, is_newuser, user_type) VALUES (%s,%s,%s,%s,TRUE,%s)'
実行したところ下記のエラーを吐きました。
```console
psycopg2.errors.NotNullViolation: null value in column "created_at" of relation "users" violates not-null constraint
DETAIL: Failing row contains (1, y.takahashi.sys20@morijyobi.ac.jp, b13edca354c927fb41626ac78656220e0e0da04eae9ee17c2fa62c75b8cb1f1e, xKzLU, 高橋 洋平, t, 0, null, null).
```
最新のDDLが手元にないので、 GoogleDocument のDDLを確認したところ NOT NULL オプションが指定されていました。このコードのSQLだと値を指定していないので、毎回 `null` で INSERT することになるため、絶対に Error を吐きます。
```sql
CREATE TABLE users (
	id          		serial,
	mail        		varchar(256)    	NOT NULL,
	password    		varchar(64)     		NOT NULL,
	salt        		varchar(32)     		NOT NULL,
	name        		varchar(64)     		NOT NULL,
	is_newuser  		boolean         		NOT NULL,
	user_type   		smallint        		NOT NULL,
	created_at  		timestamp       	NOT NULL,
	updated_at  		timestamp       	NOT NULL,
	PRIMARY KEY (id)
);
```

2022-01-14 01:00 UTC, youhei-takahashi commented on model/users.py
> +  sql = 'INSERT INTO users (mail, password, salt, name, is_newuser, user_type) VALUES (%s,%s,%s,%s,TRUE,%s)'
最新のDDLだとエラーを吐かないことを確認したためclose

2022-01-14 01:33 UTC, youhei-takahashi requested changes

2022-01-14 01:33 UTC, youhei-takahashi commented on view/teacher.py
> +      teacher_id = get_userId_with_mail(userData['担任名'])
辞書のキーの指定が間違っていました。
```suggestion
      teacher_id = get_userId_with_mail(userData['担任メールアドレス'])
```

2022-01-14 01:55 UTC, hikaru0112 commented on view/teacher.py
> +      teacher_id = get_userId_with_mail(userData['担任名'])
杞憂かもしれませんが
このコードの状態だと学生一人につき1回SELECT文が実行される為、プログラムのパフォーマンスが低下する恐れがあります。
もし先生の情報を取得するなら最初に一括で取得した方がいいような気がします

2022-01-14 01:55 UTC, hikaru0112 commented on static/js/add_user.js
> +  const checkMailTea = mail => new RegExp(/^[a-z]+\.[a-z]+@morijyobi\.ac\.jp$/).test(mail)
学生氏名では文字数カウントしていますがメールアドレスではしていない為、
サーバーエラーを起こしてしまう可能性があります。

2022-01-14 01:55 UTC, hikaru0112 commented on static/js/add_user.js
> +  //学生氏名の文字数チェック
間違ってたらすいません
教員と学生の名前をチェックしているのでこのコメントは不適切かもしれません

2022-01-18 01:19 UTC, hikaru0112 commented on model/mail.py
> +  server = smtplib.SMTP_SSL('smtp.gmail.com', 465, context=ssl.create_default_context())
SMTPに使用している465ポートなのですが、
問題なくメールを送受信できますが、
非推奨のため、587ポートの使用が望ましいと思われます

2022-01-18 01:33 UTC, hikaru0112 commented on model/mail.py
> +  server = smtplib.SMTP_SSL('smtp.gmail.com', 465, context=ssl.create_default_context())
すいません、結局2018年にまたメール用のポートとして制定された為、
問題ないです。

2022-01-18 13:27 UTC, tora87 commented on static/js/add_user.js
> +  //学生氏名の文字数チェック
その通りですね。修正しました。

2022-01-19 00:08 UTC, suzuryo-morijyobi commented on view/teacher.py
> +    csvDataMatrix = [[data.strip() for data in row.decode(encoding='shift-jis').split(',')] for row in csvdata]
import した csvライブラリを使わずに、csvを自力でパースしているの？

2022-01-19 11:28 UTC, tora87 commented on view/teacher.py
> +      teacher_id = get_userId_with_mail(userData['担任名'])
修正しました。原因はそのコードを書いた後に、CSVテンプレートの内容を変えてしまったことでした。

2022-01-19 11:30 UTC, tora87 commented on static/js/add_user.js
> +      }
#28 としてissueにあげました。

2022-01-19 11:32 UTC, tora87 commented on static/js/add_user.js
> +  const checkMailTea = mail => new RegExp(/^[a-z]+\.[a-z]+@morijyobi\.ac\.jp$/).test(mail)
メールアドレスはテーブル定義より256文字を上限として設定しました。

2022-01-21 00:51 UTC, suzuryo-morijyobi commented on static/csv/students_template.csv
> +�w�Дԍ�,����,���[���A�h���X,���ƔN�x,�S�C���[���A�h���X,,
csvファイルがshift-jisになっていますが、utf-8にしない理由は何かありますか？
日本人の名前の場合は問題になることは少ないかもしれませんが、例えば中国人が中国漢字の名前を持っている場合、shift-jisではうまく扱えないかも？

2022-01-21 01:05 UTC, suzuryo-morijyobi commented on view/teacher.py
> +    csvDataMatrix = [[data.strip() for data in row.decode(encoding='shift-jis').split(',')] for row in csvdata]
csvのデータ形式は、単純に `,` で split すれば良いというものではない。
<img width="60%" src="https://user-images.githubusercontent.com/46771743/150446600-dbe3e6db-8f13-4258-8ddf-d9a2a5d4aeb9.png">

B列ように、セルの値に `,` が入っている場合に `split(',')` をしたら意図しない所でsplitしてしまう。

C列のように、セルの中で改行がある場合、`for row in csvdata` でループを回すと、意図しない所で row が発生してしまう。

ほか `"` ダブルクォーテーションの扱いの問題もある。

各言語の csv ライブラリは、そのあたりちゃんとケアするように出来ているので、素直に csvライブラリを利用する方がいいかも。

2022-01-21 01:25 UTC, tora87 commented on static/js/add_user.js
> +  const checkMailStu = mail => new RegExp(/^[a-z]+\.[a-z]+\.sys[0-9]{2}@morijyobi\.ac\.jp$/).test(mail)
ドメインだけのチェックに修正しました。https://github.com/morijyobi-2021-itadv3/JobReportManagement/pull/22/commits/6cfac021d3bc5fdc8c88cb71a941cc8aa9e3c9cc

2022-01-21 01:26 UTC, tora87 commented on static/js/add_user.js
> +  const checkMailTea = mail => new RegExp(/^[a-z]+\.[a-z]+@morijyobi\.ac\.jp$/).test(mail)
ドメインのチェクだけなので学生と教員のメールアドレスチェックは同じ関数にしました。https://github.com/morijyobi-2021-itadv3/JobReportManagement/pull/22/commits/6cfac021d3bc5fdc8c88cb71a941cc8aa9e3c9cc

2022-01-25 03:06 UTC, tora87 commented on view/teacher.py
> +      teacher_id = get_userId_with_mail(userData['担任名'])
指摘点を修正しましたhttps://github.com/morijyobi-2021-itadv3/JobReportManagement/pull/22/commits/268146299aafe086e4c507cda0db781833b4f8c2

2022-01-25 03:10 UTC, tora87 commented on static/csv/students_template.csv
> +�w�Дԍ�,����,���[���A�h���X,���ƔN�x,�S�C���[���A�h���X,,
特に理由はなかったです。
読み込む際の文字コードとテンプレートCSVファイルの文字コードはUTF-8に変更しました。
https://github.com/morijyobi-2021-itadv3/JobReportManagement/pull/22/commits/101c54934b26329aee4bd7e38ee739a2e6ea8ec8
https://github.com/morijyobi-2021-itadv3/JobReportManagement/pull/22/commits/c9dee02460fa3b8acc542cb97470319d729591d4

2022-01-26 02:58 UTC, youhei-takahashi approved these changes

2022-01-28 01:30 UTC, tora87 commented on view/teacher.py
> +    csvDataMatrix = [[data.strip() for data in row.decode(encoding='shift-jis').split(',')] for row in csvdata]
現時点では解決ができず、時間がかかりそうなので#29 としてissueにあげました。

2022-01-28 01:31 UTC, merged