標準時変換メソッドの作成
morijyobi-2021-itadv3/JobReportManagement pull request #27
Opened 2022-01-18 03:46 UTC by hikaru0112

#23 
自分の開発する箇所でどうしても無視できない問題だったので、変換用メソッドを作成しました

2022-01-18 05:21 UTC, youhei-takahashi requested changes

2022-01-18 05:21 UTC, youhei-takahashi commented on model/time_conversion.py
> +    return date - datetime.timedelta(hours=9)
これってdockerで作成した環境上で変換テストしていますか？
計算が逆な気がするのですが・・・
![image](https://user-images.githubusercontent.com/50701460/149875585-ca31e5ba-e365-4632-bb0a-d787ad8ef33a.png)


そして引数で受け取った data のタイムゾーンを確認せず単純に計算してしまっているのも微妙です・・・。

2022-01-21 00:39 UTC, hikaru0112 commented on model/time_conversion.py
> +    return date - datetime.timedelta(hours=9)
すいません、完全に反対でした。修正しておきます。
あと、タイムゾーンに対応する処理も追加します。

2022-01-21 00:49 UTC, youhei-takahashi reviewed
UTCの環境での動作確認をしてください！

2022-01-21 01:06 UTC, hikaru0112 commented
＃ push前にimport方法を変えてしまった理由でのエラーが起きていた為修正しました。
docker上(utc)でも動作確認しました。

2022-01-21 01:20 UTC, youhei-takahashi approved these changes

2022-01-21 01:22 UTC, hikaru0112 commented
approvalいただきましたのでmergeします。

2022-01-21 01:22 UTC, merged